name: VBAN Emitter
description: Streams audio from Home Assistant to VoiceMeeter via VBAN.
version: 0.1.0
slug: vban_emitter
url: https://github.com/PBadchild/ha-vban-addon/tree/main/vban_emitter
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
hassio_role: default
map:
  - "/tmp:rw"
ports:
  6980/udp: VBAN Audio Stream
options:
  VOICEMEETER_IP: 127.0.0.1
  VBAN_PORT: 6980
  VBAN_STREAM_NAME: music_assistant
schema:
  VOICEMEETER_IP:
    name: VoiceMeeter IP Address
    description: IP of your VoiceMeeter PC (e.g., 192.168.1.100)
    required: true
    type: string
    default: 127.0.0.1
  VBAN_PORT:
    name: VBAN UDP Port
    description: Port for VBAN audio stream
    required: true
    type: integer
    default: 6980
  VBAN_STREAM_NAME:
    name: VBAN Stream Name
    description: Name for the stream in VoiceMeeter (e.g., 'music_assistant')
    required: true
    type: string
    default: music_assistant
full_time: false
privileged: false
host_network: true
audio: true
devices: []
stage: manual