name: VBAN Emitter
description: Streams audio from Home Assistant to VoiceMeeter via VBAN.
version: 0.1.0
slug: vban_emitter
url: https://github.com/PBadchild/ha-vban-addon/tree/main/vban_emitter
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
hassio_role: default
map:
  - "/tmp:rw"
ports:
  6980/udp: null
options:
  VOICEMEETER_IP: 127.0.0.1
  VBAN_PORT: 6980
  VBAN_STREAM_NAME: music_assistant
schema:
  VOICEMEETER_IP: str
  VBAN_PORT: int
  VBAN_STREAM_NAME: str
full_time: false
privileged: false
host_network: true
audio: true
devices: []
stage: experimental